###
POST http://localhost:8080/projectDAE/api/occurrences/1/documents
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJpYW5hQG1haWwucHQiLCJpYXQiOjE2NzM0ODM1MzUsImV4cCI6MTY3MzQ4NzEzNX0.n0ByZ3_JXDAg8X3p_G-1bs2AVu5SMBzuGlyCMX8wqaU
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="guitar.png"
< C:\Utilizadores\igors\imagens
--boundary

###
GET http://localhost:8080/projectDAE/api/documents/download/1
Content-Type: application/x-www-form-urlencoded